# Generated by Django 3.2.5 on 2021-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='article',
            field=models.CharField(default='x', max_length=300),
            preserve_default=False,
        ),
    ]
