# Generated by Django 3.2.5 on 2021-07-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0002_currencyunit_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityunit',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
