# Generated by Django 3.2.5 on 2021-07-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0003_quantityunit_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyunit',
            old_name='order',
            new_name='num_order',
        ),
        migrations.RenameField(
            model_name='quantityunit',
            old_name='order',
            new_name='num_order',
        ),
    ]
